/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { CryptoData, cryptoDataSchema } from './cryptoData';

export interface AllResponse {
  data?: CryptoData[];
}

export const allResponseSchema: Schema<AllResponse> = object({
  data: ['data', optional(array(lazy(() => cryptoDataSchema)))],
});
