/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface Approximations {
  liquidity?: boolean;
  marketCap?: boolean;
  price?: boolean;
}

export const approximationsSchema: Schema<Approximations> = object({
  liquidity: ['liquidity', optional(boolean())],
  marketCap: ['market_cap', optional(boolean())],
  price: ['price', optional(boolean())],
});
