/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Asset2 {
  /** The ID of the asset. */
  id?: number;
  /** The name of the asset. */
  name?: string;
  /** The symbol of the asset. */
  symbol?: string;
}

export const asset2Schema: Schema<Asset2> = object({
  id: ['id', optional(number())],
  name: ['name', optional(string())],
  symbol: ['symbol', optional(string())],
});
