/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface Asset {
  audit?: string;
  blockchains?: string[];
  circulatingSupply?: number;
  circulatingSupplyAddresses?: string[];
  contracts?: string[];
  description?: string;
  discord?: string;
  id?: number;
  kyc?: string;
  liquidity?: number;
  logo?: string;
  marketCap?: number;
  name?: string;
  price?: number;
  symbol?: string;
  totalSupply?: number;
  totalSupplyContracts?: string[];
  twitter?: string;
  volume?: number;
  website?: string;
}

export const assetSchema: Schema<Asset> = object({
  audit: ['audit', optional(string())],
  blockchains: ['blockchains', optional(array(string()))],
  circulatingSupply: ['circulating_supply', optional(number())],
  circulatingSupplyAddresses: [
    'circulating_supply_addresses',
    optional(array(string())),
  ],
  contracts: ['contracts', optional(array(string()))],
  description: ['description', optional(string())],
  discord: ['discord', optional(string())],
  id: ['id', optional(number())],
  kyc: ['kyc', optional(string())],
  liquidity: ['liquidity', optional(number())],
  logo: ['logo', optional(string())],
  marketCap: ['market_cap', optional(number())],
  name: ['name', optional(string())],
  price: ['price', optional(number())],
  symbol: ['symbol', optional(string())],
  totalSupply: ['total_supply', optional(number())],
  totalSupplyContracts: ['total_supply_contracts', optional(array(string()))],
  twitter: ['twitter', optional(string())],
  volume: ['volume', optional(number())],
  website: ['website', optional(string())],
});
