/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { lazy, object, optional } from '../schema';
import { dataSchema } from './data';
export const assetSchema = object({
    data: ['data', optional(lazy(() => dataSchema))],
});
//# sourceMappingURL=asset.js.map