/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Data, dataSchema } from './data';

export interface Asset {
  data?: Data;
}

export const assetSchema: Schema<Asset> = object({
  data: ['data', optional(lazy(() => dataSchema))],
});
