/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { Schema } from '../schema';
export interface Asset4 {
    name?: string;
    symbol?: string;
    id?: number;
    contracts?: string[];
    logo?: string;
}
export declare const asset4Schema: Schema<Asset4>;
