/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, lazy, number, object, optional, Schema } from '../schema';
import { Asset4, asset4Schema } from './asset4';
import {
  CrossChainBalances,
  crossChainBalancesSchema,
} from './crossChainBalances';

export interface Asset3 {
  asset?: Asset4;
  price?: number;
  estimatedBalance?: number;
  tokenBalance?: number;
  crossChainBalances?: Record<string, CrossChainBalances>;
}

export const asset3Schema: Schema<Asset3> = object({
  asset: ['asset', optional(lazy(() => asset4Schema))],
  price: ['price', optional(number())],
  estimatedBalance: ['estimated_balance', optional(number())],
  tokenBalance: ['token_balance', optional(number())],
  crossChainBalances: [
    'cross_chain_balances',
    optional(dict(lazy(() => crossChainBalancesSchema))),
  ],
});
