/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { dict, lazy, number, object, optional } from '../schema';
import { asset4Schema } from './asset4';
import { crossChainBalancesSchema, } from './crossChainBalances';
export const asset3Schema = object({
    asset: ['asset', optional(lazy(() => asset4Schema))],
    price: ['price', optional(number())],
    estimatedBalance: ['estimated_balance', optional(number())],
    tokenBalance: ['token_balance', optional(number())],
    crossChainBalances: [
        'cross_chain_balances',
        optional(dict(lazy(() => crossChainBalancesSchema))),
    ],
});
//# sourceMappingURL=asset3.js.map