/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, lazy, number, object, optional, Schema } from '../schema';
import { Asset, assetSchema } from './asset';
import {
  CrossChainBalances,
  crossChainBalancesSchema,
} from './crossChainBalances';

export interface Asset5 {
  asset?: Asset;
  /** Current price of the asset. */
  price?: number;
  /** Estimated balance of the asset in the wallet. */
  estimatedBalance?: number;
  /** Token balance of the asset in the wallet. */
  tokenBalance?: number;
  crossChainBalances?: Record<string, CrossChainBalances>;
}

export const asset5Schema: Schema<Asset5> = object({
  asset: ['asset', optional(lazy(() => assetSchema))],
  price: ['price', optional(number())],
  estimatedBalance: ['estimated_balance', optional(number())],
  tokenBalance: ['token_balance', optional(number())],
  crossChainBalances: [
    'cross_chain_balances',
    optional(dict(lazy(() => crossChainBalancesSchema))),
  ],
});
