/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface AssetTransaction {
  name?: string;
  symbol?: string;
  id?: number;
  contract?: string;
  logo?: string;
}

export const assetTransactionSchema: Schema<AssetTransaction> = object({
  name: ['name', optional(string())],
  symbol: ['symbol', optional(string())],
  id: ['id', optional(number())],
  contract: ['contract', optional(string())],
  logo: ['logo', optional(string())],
});
