/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface CrossChainBalances {
  address?: string;
  balance?: number;
  balanceRaw?: string;
  chainId?: number;
}

export const crossChainBalancesSchema: Schema<CrossChainBalances> = object({
  address: ['address', optional(string())],
  balance: ['balance', optional(number())],
  balanceRaw: ['balanceRaw', optional(string())],
  chainId: ['chainId', optional(number())],
});
