/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface CryptoData {
  /** The blockchains on which the cryptocurrency exists */
  blockchains?: (string | null)[];
  /** The unique identifier of the cryptocurrency */
  id?: number;
  /** The name of the cryptocurrency */
  name?: string;
  /** The symbol of the cryptocurrency */
  symbol?: string | null;
}

export const cryptoDataSchema: Schema<CryptoData> = object({
  blockchains: ['blockchains', optional(array(nullable(string())))],
  id: ['id', optional(number())],
  name: ['name', optional(string())],
  symbol: ['symbol', optional(nullable(string()))],
});
