/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Asset3, asset3Schema } from './asset3';
import { LastUpdated, lastUpdatedSchema } from './lastUpdated';

export interface Data5 {
  totalWalletBalance?: number;
  wallet?: string;
  assets?: Asset3[];
  lastUpdated?: Record<string, LastUpdated>;
}

export const data5Schema: Schema<Data5> = object({
  totalWalletBalance: ['total_wallet_balance', optional(number())],
  wallet: ['wallet', optional(string())],
  assets: ['assets', optional(array(lazy(() => asset3Schema)))],
  lastUpdated: ['lastUpdated', optional(dict(lazy(() => lastUpdatedSchema)))],
});
