/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface Data {
  id?: number;
  name?: string;
  symbol?: string;
  contracts?: (string | null)[];
  blockchains?: string[];
  twitter?: string | null;
  website?: string | null;
  logo?: string;
  price?: number;
  marketCap?: number;
  liquidity?: number;
  volume?: number;
  description?: string;
  kyc?: string | null;
  audit?: string | null;
  totalSupplyContracts?: string[] | null;
  totalSupply?: number;
  circulatingSupply?: number;
  circulatingSupplyAddresses?: string[];
  discord?: string | null;
  maxSupply?: number;
  chat?: string | null;
}

export const dataSchema: Schema<Data> = object({
  id: ['id', optional(number())],
  name: ['name', optional(string())],
  symbol: ['symbol', optional(string())],
  contracts: ['contracts', optional(array(nullable(string())))],
  blockchains: ['blockchains', optional(array(string()))],
  twitter: ['twitter', optional(nullable(string()))],
  website: ['website', optional(nullable(string()))],
  logo: ['logo', optional(string())],
  price: ['price', optional(number())],
  marketCap: ['market_cap', optional(number())],
  liquidity: ['liquidity', optional(number())],
  volume: ['volume', optional(number())],
  description: ['description', optional(string())],
  kyc: ['kyc', optional(nullable(string()))],
  audit: ['audit', optional(nullable(string()))],
  totalSupplyContracts: [
    'total_supply_contracts',
    optional(nullable(array(string()))),
  ],
  totalSupply: ['total_supply', optional(number())],
  circulatingSupply: ['circulating_supply', optional(number())],
  circulatingSupplyAddresses: [
    'circulating_supply_addresses',
    optional(array(string())),
  ],
  discord: ['discord', optional(nullable(string()))],
  maxSupply: ['max_supply', optional(number())],
  chat: ['chat', optional(nullable(string()))],
});
