/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { array, lazy, number, object, optional, string, } from '../schema';
import { asset5Schema } from './asset5';
export const data8Schema = object({
    totalWalletBalance: ['total_wallet_balance', optional(number())],
    wallet: ['wallet', optional(string())],
    assets: ['assets', optional(array(lazy(() => asset5Schema)))],
});
//# sourceMappingURL=data8.js.map