/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Pair2, pair2Schema } from './pair2';

export interface Data1 {
  pairs?: Pair2[];
}

export const data1Schema: Schema<Data1> = object({
  pairs: ['pairs', optional(array(lazy(() => pair2Schema)))],
});
