/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface Data4 {
  wallet?: string[];
  balanceUsd?: number;
  balanceHistory?: unknown[];
}

export const data4Schema: Schema<Data4> = object({
  wallet: ['wallet', optional(array(string()))],
  balanceUsd: ['balance_usd', optional(number())],
  balanceHistory: ['balance_history', optional(array(unknown()))],
});
