/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Asset5, asset5Schema } from './asset5';

export interface Data8 {
  /** Total balance of the wallet in USD. */
  totalWalletBalance?: number;
  /** Wallet address queried. */
  wallet?: string;
  assets?: Asset5[];
}

export const data8Schema: Schema<Data8> = object({
  totalWalletBalance: ['total_wallet_balance', optional(number())],
  wallet: ['wallet', optional(string())],
  assets: ['assets', optional(array(lazy(() => asset5Schema)))],
});
