/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { array, lazy, object, optional } from '../schema';
import { multiPairSchema } from './multiPair';
export const data7Schema = object({
    pairs: ['pairs', optional(array(lazy(() => multiPairSchema)))],
});
//# sourceMappingURL=data7.js.map