/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { MultiPair, multiPairSchema } from './multiPair';

export interface Data7 {
  pairs?: MultiPair[];
}

export const data7Schema: Schema<Data7> = object({
  pairs: ['pairs', optional(array(lazy(() => multiPairSchema)))],
});
