/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, unknown } from '../schema';

export interface Data2 {
  priceHistory?: unknown[];
}

export const data2Schema: Schema<Data2> = object({
  priceHistory: ['price_history', optional(array(unknown()))],
});
