/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, dict, lazy, number, object, optional, Schema } from '../schema';
import { LastUpdated2, lastUpdated2Schema } from './lastUpdated2';
import { Transaction, transactionSchema } from './transaction';

export interface Data9 {
  transactions?: Transaction[];
  /** Total number of transactions. */
  total?: number;
  /** Offset value for pagination. */
  offset?: number;
  /** Limit value for pagination. */
  limit?: number;
  /** Current page number. */
  page?: number;
  lastUpdated?: Record<string, LastUpdated2>;
}

export const data9Schema: Schema<Data9> = object({
  transactions: [
    'transactions',
    optional(array(lazy(() => transactionSchema))),
  ],
  total: ['total', optional(number())],
  offset: ['offset', optional(number())],
  limit: ['limit', optional(number())],
  page: ['page', optional(number())],
  lastUpdated: ['lastUpdated', optional(dict(lazy(() => lastUpdated2Schema)))],
});
