/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Datum {
  tokenAddress: string;
  tokenId: string;
  amount: string;
  tokenHash: string;
  contractType: string;
  name: string;
  symbol: string;
  tokenUri: string;
  metadata: string;
}

export const datumSchema: Schema<Datum> = object({
  tokenAddress: ['token_address', string()],
  tokenId: ['token_id', string()],
  amount: ['amount', string()],
  tokenHash: ['token_hash', string()],
  contractType: ['contract_type', string()],
  name: ['name', string()],
  symbol: ['symbol', string()],
  tokenUri: ['token_uri', string()],
  metadata: ['metadata', string()],
});
