/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { number, object, optional } from '../schema';
export const detailedBalanceSchema = object({
    balance: ['balance', optional(number())],
    balanceUsd: ['balance_usd', optional(number())],
});
//# sourceMappingURL=detailedBalance.js.map