/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface DetailedBalance {
  balance?: number;
  balanceUsd?: number;
}

export const detailedBalanceSchema: Schema<DetailedBalance> = object({
  balance: ['balance', optional(number())],
  balanceUsd: ['balance_usd', optional(number())],
});
