/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface LastUpdated {
  normal?: number;
  internal?: number;
  token?: number;
  lastUpdated?: number;
}

export const lastUpdatedSchema: Schema<LastUpdated> = object({
  normal: ['normal', optional(number())],
  internal: ['internal', optional(number())],
  token: ['token', optional(number())],
  lastUpdated: ['last_updated', optional(number())],
});
