/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Pair, pairSchema } from './pair';

export interface MarketPairResponse {
  data?: Pair;
}

export const marketPairResponseSchema: Schema<MarketPairResponse> = object({
  data: ['data', optional(lazy(() => pairSchema))],
});
