/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  MarketDataPairResponse,
  marketDataPairResponseSchema,
} from './marketDataPairResponse';

export interface MarketPairResponse {
  data?: MarketDataPairResponse;
}

export const marketPairResponseSchema: Schema<MarketPairResponse> = object({
  data: ['data', optional(lazy(() => marketDataPairResponseSchema))],
});
