/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Data7, data7Schema } from './data7';

export interface MarketPairsResponse {
  data?: Data7;
}

export const marketPairsResponseSchema: Schema<MarketPairsResponse> = object({
  data: ['data', optional(lazy(() => data7Schema))],
});
