/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { boolean, number, object, optional } from '../schema';
export const marketMetricsSchema = object({
    marketCap: ['market_cap', optional(number())],
    marketCapDiluted: ['market_cap_diluted', optional(number())],
    liquidity: ['liquidity', optional(number())],
    liquidityChange24h: ['liquidity_change_24h', optional(number())],
    price: ['price', optional(number())],
    offChainVolume: ['off_chain_volume', optional(number())],
    volume: ['volume', optional(number())],
    volumeChange24h: ['volume_change_24h', optional(number())],
    volume7d: ['volume_7d', optional(number())],
    isListed: ['is_listed', optional(boolean())],
    priceChange24h: ['price_change_24h', optional(number())],
    priceChange1h: ['price_change_1h', optional(number())],
    priceChange7d: ['price_change_7d', optional(number())],
    priceChange1m: ['price_change_1m', optional(number())],
    priceChange1y: ['price_change_1y', optional(number())],
    ath: ['ath', optional(number())],
    atl: ['atl', optional(number())],
});
//# sourceMappingURL=marketMetrics.js.map