/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema } from '../schema';

export interface MarketMetrics {
  /** The market capitalization of the cryptocurrency. */
  marketCap?: number;
  /** The diluted market capitalization of the cryptocurrency. */
  marketCapDiluted?: number;
  /** The liquidity of the cryptocurrency. */
  liquidity?: number;
  /** The 24-hour change in liquidity. */
  liquidityChange24h?: number;
  /** The current price of the cryptocurrency. */
  price?: number;
  /** The off-chain trading volume. */
  offChainVolume?: number;
  /** The trading volume of the cryptocurrency. */
  volume?: number;
  /** The 24-hour change in trading volume. */
  volumeChange24h?: number;
  /** The 7-day trading volume. */
  volume7d?: number;
  /** Indicates whether the cryptocurrency is listed or not. */
  isListed?: boolean;
  /** The 24-hour price change. */
  priceChange24h?: number;
  /** The 1-hour price change. */
  priceChange1h?: number;
  /** The 7-day price change. */
  priceChange7d?: number;
  /** The 1-month price change. */
  priceChange1m?: number;
  /** The 1-year price change. */
  priceChange1y?: number;
  /** The all-time high price. */
  ath?: number;
  /** The all-time low price. */
  atl?: number;
}

export const marketMetricsSchema: Schema<MarketMetrics> = object({
  marketCap: ['market_cap', optional(number())],
  marketCapDiluted: ['market_cap_diluted', optional(number())],
  liquidity: ['liquidity', optional(number())],
  liquidityChange24h: ['liquidity_change_24h', optional(number())],
  price: ['price', optional(number())],
  offChainVolume: ['off_chain_volume', optional(number())],
  volume: ['volume', optional(number())],
  volumeChange24h: ['volume_change_24h', optional(number())],
  volume7d: ['volume_7d', optional(number())],
  isListed: ['is_listed', optional(boolean())],
  priceChange24h: ['price_change_24h', optional(number())],
  priceChange1h: ['price_change_1h', optional(number())],
  priceChange7d: ['price_change_7d', optional(number())],
  priceChange1m: ['price_change_1m', optional(number())],
  priceChange1y: ['price_change_1y', optional(number())],
  ath: ['ath', optional(number())],
  atl: ['atl', optional(number())],
});
