/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { Schema } from '../schema';
import { Pair } from './pair';
export interface MarketPairResponse {
    data?: Pair;
}
export declare const marketPairResponseSchema: Schema<MarketPairResponse>;
