/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { Schema } from '../schema';
import { Data2 } from './data2';
export interface MarketHistoryResponse {
    data?: Data2;
}
export declare const marketHistoryResponseSchema: Schema<MarketHistoryResponse>;
