/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { lazy, object, optional } from '../schema';
import { data2Schema } from './data2';
export const marketHistoryResponseSchema = object({ data: ['data', optional(lazy(() => data2Schema))] });
//# sourceMappingURL=marketHistoryResponse.js.map