/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, number, object, optional, Schema } from '../schema';
import { Approximations, approximationsSchema } from './approximations';

export interface MarketMetrics {
  approximations?: Approximations;
  isListed?: boolean;
  liquidity?: number;
  marketCap?: number;
  price?: number;
  volume?: number;
  volume7d?: number;
}

export const marketMetricsSchema: Schema<MarketMetrics> = object({
  approximations: [
    'approximations',
    optional(lazy(() => approximationsSchema)),
  ],
  isListed: ['is_listed', optional(boolean())],
  liquidity: ['liquidity', optional(number())],
  marketCap: ['market_cap', optional(number())],
  price: ['price', optional(number())],
  volume: ['volume', optional(number())],
  volume7d: ['volume_7d', optional(number())],
});
