/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { MarketMetrics, marketMetricsSchema } from './marketMetrics';

export interface MarketDataResponse {
  data?: MarketMetrics;
}

export const marketDataResponseSchema: Schema<MarketDataResponse> = object({
  data: ['data', optional(lazy(() => marketMetricsSchema))],
});
