/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema } from '../schema';

export interface MarketHistoryResponse {
  priceHistory?: number[];
}

export const marketHistoryResponseSchema: Schema<MarketHistoryResponse> = object(
  { priceHistory: ['price_history', optional(array(number()))] }
);
