/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  MarketDataPairResponse,
  marketDataPairResponseSchema,
} from './marketDataPairResponse';

export interface MarketPairsResponse {
  data?: MarketDataPairResponse[];
}

export const marketPairsResponseSchema: Schema<MarketPairsResponse> = object({
  data: ['data', optional(array(lazy(() => marketDataPairResponseSchema)))],
});
