/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  MarketDataResponse,
  marketDataResponseSchema,
} from './marketDataResponse';

export interface MarketDataResponse1 {
  data?: MarketDataResponse;
}

export const marketDataResponse1Schema: Schema<MarketDataResponse1> = object({
  data: ['data', optional(lazy(() => marketDataResponseSchema))],
});
