/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Trade, tradeSchema } from './trade';

export interface MarketTradesResponse {
  trades?: Trade[];
}

export const marketTradesResponseSchema: Schema<MarketTradesResponse> = object({
  trades: ['trades', optional(array(lazy(() => tradeSchema)))],
});
