/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Data2, data2Schema } from './data2';

export interface MarketHistoryResponse {
  data?: Data2;
}

export const marketHistoryResponseSchema: Schema<MarketHistoryResponse> = object(
  { data: ['data', optional(lazy(() => data2Schema))] }
);
