/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { Schema } from '../schema';
export interface MarketMetrics {
    /** The market capitalization of the cryptocurrency. */
    marketCap?: number;
    /** The diluted market capitalization of the cryptocurrency. */
    marketCapDiluted?: number;
    /** The liquidity of the cryptocurrency. */
    liquidity?: number;
    /** The 24-hour change in liquidity. */
    liquidityChange24h?: number;
    /** The current price of the cryptocurrency. */
    price?: number;
    /** The off-chain trading volume. */
    offChainVolume?: number;
    /** The trading volume of the cryptocurrency. */
    volume?: number;
    /** The 24-hour change in trading volume. */
    volumeChange24h?: number;
    /** The 7-day trading volume. */
    volume7d?: number;
    /** Indicates whether the cryptocurrency is listed or not. */
    isListed?: boolean;
    /** The 24-hour price change. */
    priceChange24h?: number;
    /** The 1-hour price change. */
    priceChange1h?: number;
    /** The 7-day price change. */
    priceChange7d?: number;
    /** The 1-month price change. */
    priceChange1m?: number;
    /** The 1-year price change. */
    priceChange1y?: number;
    /** The all-time high price. */
    ath?: number;
    /** The all-time low price. */
    atl?: number;
}
export declare const marketMetricsSchema: Schema<MarketMetrics>;
