/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { Schema } from '../schema';
import { MarketMetrics } from './marketMetrics';
export interface MultiDataResponse {
    data?: Record<string, MarketMetrics>;
}
export declare const multiDataResponseSchema: Schema<MultiDataResponse>;
