/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, lazy, object, optional, Schema } from '../schema';
import { MarketMetrics, marketMetricsSchema } from './marketMetrics';

export interface MultiDataResponse {
  data?: Record<string, MarketMetrics>;
}

export const multiDataResponseSchema: Schema<MultiDataResponse> = object({
  data: ['data', optional(dict(lazy(() => marketMetricsSchema)))],
});
