/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { Schema } from '../schema';
import { Token01 } from './token01';
export interface Pair {
    token0?: Token01;
    token1?: Token01;
}
export declare const pairSchema: Schema<Pair>;
