/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Token01, token01Schema } from './token01';

export interface Pair {
  token0?: Token01;
  token1?: Token01;
}

export const pairSchema: Schema<Pair> = object({
  token0: ['token0', optional(lazy(() => token01Schema))],
  token1: ['token1', optional(lazy(() => token01Schema))],
});
