/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { lazy, object, optional } from '../schema';
import { asset2Schema } from './asset2';
import { quoteSchema } from './quote';
export const quoteResponseSchema = object({
    asset: ['asset', optional(lazy(() => asset2Schema))],
    quote: ['quote', optional(lazy(() => quoteSchema))],
});
//# sourceMappingURL=quoteResponse.js.map