/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface Quote {
  /** The market cap of the asset. */
  marketCap?: number;
  /** The price of the asset. */
  price?: number;
  /** The volume of the asset. */
  volume?: number;
}

export const quoteSchema: Schema<Quote> = object({
  marketCap: ['market_cap', optional(number())],
  price: ['price', optional(number())],
  volume: ['volume', optional(number())],
});
