/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Asset2, asset2Schema } from './asset2';
import { Quote, quoteSchema } from './quote';

export interface QuoteResponse {
  asset?: Asset2;
  quote?: Quote;
}

export const quoteResponseSchema: Schema<QuoteResponse> = object({
  asset: ['asset', optional(lazy(() => asset2Schema))],
  quote: ['quote', optional(lazy(() => quoteSchema))],
});
