/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Success, successSchema } from './success';

export interface QuoteResponse1 {
  success?: Success[];
}

export const quoteResponse1Schema: Schema<QuoteResponse1> = object({
  success: ['success', optional(array(lazy(() => successSchema)))],
});
