/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { SearchCryptoData, searchCryptoDataSchema } from './searchCryptoData';

export interface SearchResponse {
  data?: SearchCryptoData[];
}

export const searchResponseSchema: Schema<SearchResponse> = object({
  data: ['data', optional(array(lazy(() => searchCryptoDataSchema)))],
});
