/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { Schema } from '../schema';
export interface Token0 {
    address?: string;
    decimals?: number;
    symbol?: string;
    name?: string;
    logo?: string;
    price?: number;
    priceToken?: number;
    id?: number;
}
export declare const token0Schema: Schema<Token0>;
