/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';

export interface Token02 {
  address?: string;
  decimals?: number;
  symbol?: string;
  name?: string;
  logo?: string;
  price?: number;
  priceToken?: number | null;
  id?: number;
}

export const token02Schema: Schema<Token02> = object({
  address: ['address', optional(string())],
  decimals: ['decimals', optional(number())],
  symbol: ['symbol', optional(string())],
  name: ['name', optional(string())],
  logo: ['logo', optional(string())],
  price: ['price', optional(number())],
  priceToken: ['priceToken', optional(nullable(number()))],
  id: ['id', optional(number())],
});
