/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Token01 {
  address?: string;
  name?: string;
  price?: number;
  priceToken?: number;
}

export const token01Schema: Schema<Token01> = object({
  address: ['address', optional(string())],
  name: ['name', optional(string())],
  price: ['price', optional(number())],
  priceToken: ['priceToken', optional(number())],
});
