/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { Schema } from '../schema';
import { Data3 } from './data3';
export interface TradeHistoryResponse {
    data?: Data3[];
}
export declare const tradeHistoryResponseSchema: Schema<TradeHistoryResponse>;
