/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { array, lazy, object, optional } from '../schema';
import { data3Schema } from './data3';
export const tradeHistoryResponseSchema = object({
    data: ['data', optional(array(lazy(() => data3Schema)))],
});
//# sourceMappingURL=tradeHistoryResponse.js.map