/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { Asset1, asset1Schema } from './asset1';

export interface Transaction {
  /** The amount of asset in the transaction. */
  amount?: number;
  asset?: Asset1;
  /** The sender's address. */
  from?: string;
  /** The timestamp of the transaction. */
  timestamp?: number;
  /** The receiver's address. */
  to?: string;
}

export const transactionSchema: Schema<Transaction> = object({
  amount: ['amount', optional(number())],
  asset: ['asset', optional(lazy(() => asset1Schema))],
  from: ['from', optional(string())],
  timestamp: ['timestamp', optional(number())],
  to: ['to', optional(string())],
});
