/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { Schema } from '../schema';
import { AssetTransaction } from './assetTransaction';
export interface Transaction {
    timestamp?: number;
    asset?: AssetTransaction;
    type?: string;
    methodId?: string | null;
    hash?: string;
    blockchain?: string;
    amount?: number;
    amountUsd?: number;
    to?: string;
    from?: string;
    txCost?: number;
}
export declare const transactionSchema: Schema<Transaction>;
