/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Tx {
  data?: string;
  from?: string;
  to?: string;
  value?: string;
}

export const txSchema: Schema<Tx> = object({
  data: ['data', optional(string())],
  from: ['from', optional(string())],
  to: ['to', optional(string())],
  value: ['value', optional(string())],
});
