/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { stringEnum } from '../schema';
/**
 * Enum for TypeEnum
 */
export var TypeEnum;
(function (TypeEnum) {
    TypeEnum["Fast"] = "fast";
    TypeEnum["Best"] = "best";
})(TypeEnum || (TypeEnum = {}));
/**
 * Schema for TypeEnum
 */
export const typeEnumSchema = stringEnum(TypeEnum);
//# sourceMappingURL=typeEnum.js.map