/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { Schema } from '../schema';
import { Data4 } from './data4';
export interface WalletHistoryResponse {
    data?: Data4;
}
export declare const walletHistoryResponseSchema: Schema<WalletHistoryResponse>;
