/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { lazy, object, optional } from '../schema';
import { data5Schema } from './data5';
export const walletPortfolioResponseSchema = object({ data: ['data', optional(lazy(() => data5Schema))] });
//# sourceMappingURL=walletPortfolioResponse.js.map