/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { Schema } from '../schema';
import { Data5 } from './data5';
export interface WalletPortfolioResponse {
    data?: Data5;
}
export declare const walletPortfolioResponseSchema: Schema<WalletPortfolioResponse>;
