/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { Schema } from '../schema';
import { NFTTransaction } from './nFTTransaction';
export interface WalletNFTsResponse {
    transactions?: NFTTransaction[];
}
export declare const walletNFTsResponseSchema: Schema<WalletNFTsResponse>;
