/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface WalletHistoryResponse {
  balanceHistory?: number[];
  balanceUsd?: number;
  wallet?: string;
}

export const walletHistoryResponseSchema: Schema<WalletHistoryResponse> = object(
  {
    balanceHistory: ['balance_history', optional(array(number()))],
    balanceUsd: ['balance_usd', optional(number())],
    wallet: ['wallet', optional(string())],
  }
);
