/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { Schema } from '../schema';
import { Data9 } from './data9';
export interface WalletTransactionsResponse {
    data?: Data9;
}
export declare const walletTransactionsResponseSchema: Schema<WalletTransactionsResponse>;
