/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Transaction, transactionSchema } from './transaction';

export interface WalletTransactionsResponse {
  transactions?: Transaction[];
}

export const walletTransactionsResponseSchema: Schema<WalletTransactionsResponse> = object(
  {
    transactions: [
      'transactions',
      optional(array(lazy(() => transactionSchema))),
    ],
  }
);
