/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, lazy, object, optional, Schema } from '../schema';
import { Data8, data8Schema } from './data8';
import { LastUpdated1, lastUpdated1Schema } from './lastUpdated1';

export interface WalletPortfolioResponse1 {
  data?: Data8;
  lastUpdated?: Record<string, LastUpdated1>;
}

export const walletPortfolioResponse1Schema: Schema<WalletPortfolioResponse1> = object(
  {
    data: ['data', optional(lazy(() => data8Schema))],
    lastUpdated: [
      'lastUpdated',
      optional(dict(lazy(() => lastUpdated1Schema))),
    ],
  }
);
