/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { lazy, object, optional } from '../schema';
import { data4Schema } from './data4';
export const walletHistoryResponseSchema = object({ data: ['data', optional(lazy(() => data4Schema))] });
//# sourceMappingURL=walletHistoryResponse.js.map