/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Data4, data4Schema } from './data4';

export interface WalletHistoryResponse {
  data?: Data4;
}

export const walletHistoryResponseSchema: Schema<WalletHistoryResponse> = object(
  { data: ['data', optional(lazy(() => data4Schema))] }
);
