/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Data9, data9Schema } from './data9';

export interface WalletTransactionsResponse {
  data?: Data9;
}

export const walletTransactionsResponseSchema: Schema<WalletTransactionsResponse> = object(
  { data: ['data', optional(lazy(() => data9Schema))] }
);
