/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */
import { Schema } from '../schema';
import { Data6 } from './data6';
export interface WalletNftsResponse1 {
    data?: Data6[];
}
export declare const walletNftsResponse1Schema: Schema<WalletNftsResponse1>;
