/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Data6, data6Schema } from './data6';

export interface WalletNftsResponse1 {
  data?: Data6[];
}

export const walletNftsResponse1Schema: Schema<WalletNftsResponse1> = object({
  data: ['data', optional(array(lazy(() => data6Schema)))],
});
